services:
  - type: web
    name: pokedexapp
    env: docker
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: MONGODB_URI
        value: ${MONGODB_URI}
      - key: PORT
        value: ${PORT}
      - key: DEFAULT_LIMIT
        value: ${DEFAULT_LIMIT}
    ports:
      - name: http
        port: ${PORT}
    dependsOn:
      - name: mongo-db

  - type: service
    name: mongo-db
    env: docker
    dockerfilePath: ""
    image: mongo:5
    volumes:
      - path: /data/db
        name: mongo-data
    envVars:
      - key: MONGODB_DATABASE
        value: nest-pokemon
    ports:
      - name: mongo
        port: 27017