services:
  - type: web
    name: pokedexapp
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    buildCommand: "docker-compose -f docker-compose.prod.yaml up --build"
    startCommand: "docker-compose -f docker-compose.prod.yaml up"
    envVars:
      - key: MONGODB_URI
        value: ${MONGODB_URI}
      - key: PORT
        value: ${PORT}
      - key: DEFAULT_LIMIT
        value: ${DEFAULT_LIMIT}
    ports:
      - port: ${PORT}